import parsedModules from "virtual:md-content";
import { useMemo } from "react";

/**
 * Indexes all .md files under /src/content/ using a single virtual module
 * (`virtual:md-content`) generated by the vite-plugin-md-content Vite plugin.
 * All markdown is pre-parsed at build/dev time — the browser receives one JS
 * module containing every file's { data, content }. Zero runtime network
 * requests, no gray-matter or Buffer in the browser bundle.
 *
 * Content structure:
 *   src/content/{Group}.md           → group header file (displayed when group is selected)
 *   src/content/{Group}/{item}.md    → sub-content item
 *
 * Header files are detected by path depth: direct children of content/ (depth 1)
 * are headers; files inside subfolders (depth 2+) are regular items.
 * Header file names must match the group id in config exactly (case-sensitive).
 *
 * Return values:
 *   index          – { [id]: frontmatter }   (all metadata, content excluded)
 *   getContent(id) – string | null           (markdown body, synchronous)
 */

export interface ContentEntry {
  id: string;
  group?: string;
  title?: string;
  subtitle?: string;
  start?: string;
  end?: string;
  className?: string;
  type?: string;
  tags?: string[];
  location?: { lat: number; lng: number; label?: string };
  polygon?: [number, number][];
  sidebarSort?: string;
  _path: string;
  _isHeader: boolean;
  [key: string]: unknown;
}

export interface ContentIndex {
  [id: string]: ContentEntry;
}

/** Shape of a pre-parsed .md module (emitted by vite-plugin-md-content) */
export interface MdModule {
  data: Record<string, unknown>;
  content: string;
}

/** Content root prefix used to calculate path depth */
const CONTENT_PREFIX = "../content/";

/**
 * Derive id from path.
 * Header files:  "../content/Cinema.md" → "Cinema"
 * Content files: "../content/Cinema/Hero (2002).md" → "Hero (2002)"
 */
export function pathToId(path: string): string {
  return (path.split("/").pop() ?? "").replace(".md", "");
}

/**
 * A file is a group header when it sits directly under the content root,
 * i.e. the relative part after "../content/" contains no "/" separator.
 */
export function isHeaderPath(path: string): boolean {
  const rel = path.slice(CONTENT_PREFIX.length); // e.g. "Cinema.md" or "Cinema/Hero (2002).md"
  return !rel.includes("/");
}

/**
 * Build the content index synchronously from pre-parsed modules.
 * Runs once at module scope — the index is static and never changes at runtime.
 */
export function buildIndex(modules: Record<string, MdModule>): ContentIndex {
  const entries: ContentIndex = {};
  for (const [path, mod] of Object.entries(modules)) {
    const id = pathToId(path);
    try {
      entries[id] = {
        id,
        ...mod.data,
        _path: path,
        _isHeader: isHeaderPath(path),
      } as ContentEntry;
    } catch (e) {
      console.warn("MD parse error:", path, e);
    }
  }
  return entries;
}

/** Module-level singleton index — available synchronously on first render */
const staticIndex: ContentIndex = buildIndex(parsedModules);

/**
 * Retrieve the markdown body (excluding front matter) for a given content id.
 * Synchronous — content is already pre-parsed by the Vite plugin.
 */
function getContentById(id: string): string | null {
  const meta = staticIndex[id];
  if (!meta) return null;

  const mod = parsedModules[meta._path];
  if (!mod) return null;

  return mod.content;
}

export function useMdLoader() {
  const index = useMemo(() => staticIndex, []);
  const getContent = useMemo(() => getContentById, []);

  return { index, getContent };
}
